### ISSUE TITLE
No resources on path

### ISSUE THREAD

**Issue by aloon** [toddfast/mutagen-cassandra#1]
no matter where I put the mutations 

```
mutagen.initialize("resources/mutations");
```

or absolute path
I always have:

```
Exception in thread "main" java.lang.IllegalArgumentException: No resources on path "resources/mutations" were found
    at com.toddfast.mutagen.basic.ResourceScanner.getResources(ResourceScanner.java:49)
    at com.toddfast.mutagen.cassandra.impl.CassandraMutagenImpl.initialize(CassandraMutagenImpl.java:39)
    at asdf.qwer.App.main(App.java:30)
```

Thanks

**Comment by vbabak** [comment]
I have the same error. Have you resolved this already?
